name: Midnight

concurrency:
  group: bishop-production
  cancel-in-progress: true

on:
  pull_request:
    branches: 
      - main
    types: [closed]

jobs:
  build:
    if: ${{ github.event.pull_request.merged }}
    runs-on: self-hosted

    steps:
    - name: Shlag's Clean
      run: |
        ls -la ./
        rm -rf ./* || true
        rm -rf ./.??* || true
        ls -la ./
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Install Transcrypt
      run: git clone https://github.com/elasticdog/transcrypt.git build/transcrypt
    - name: Decrypt
      run: build/transcrypt/transcrypt -y -c aes-256-cbc -p '${{ secrets.TranscryptKey }}'
    - name: Build Image
      run: docker-compose build
    - name: Mount Image
      run: docker-compose up -d
