name: Midnight

concurrency:
  group: bishop-production
  cancel-in-progress: true

on:
  pull_request:
    branches: 
      - main
    types: [closed]

jobs:
  build:
    if: ${{ github.event.pull_request.merged }}
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Decrypt
      run: ./.transcrypt/transcrypt -c aes-256-cbc -p '${{ secrets.TranscryptKey }}' -y
    - name: Build Image
      run: docker-compose build
    - name: Mount Image
      run: docker-compose up -d